"""Type stubs for the C++ _core extension module."""

import numpy as np
import numpy.typing as npt

class Rng:
    def __init__(self, seed: int) -> None: ...
    def uniform(self) -> float: ...
    def rand_below(self, n: int) -> int: ...
    def jump(self) -> None: ...

def make_neighbor_table(L: int) -> npt.NDArray[np.int32]: ...

class IsingModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def spins(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the spin array, dtype int8."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_spin(self, site: int, value: int) -> None: ...
    def energy(self) -> int: ...
    def magnetization(self) -> float: ...
    def abs_magnetization(self) -> float: ...
    def _wolff_step(self) -> int: ...
    def _delta_energy(self, site: int) -> int: ...
    def _metropolis_sweep(self) -> int: ...
    def sweep(self, n_sweeps: int) -> dict[str, npt.NDArray[np.int32 | np.float64]]: ...

class BlumeCapelModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def D(self) -> float: ...
    @property
    def spins(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the spin array, dtype int8."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_crystal_field(self, D: float) -> None: ...
    def set_spin(self, site: int, value: int) -> None: ...
    def energy(self) -> float: ...
    def magnetization(self) -> float: ...
    def abs_magnetization(self) -> float: ...
    def quadrupole(self) -> float: ...
    def _wolff_step(self) -> int: ...
    def _delta_energy(self, site: int, new_spin: int) -> float: ...
    def _metropolis_sweep(self) -> int: ...
    def sweep(self, n_sweeps: int) -> dict[str, npt.NDArray[np.float64]]: ...

class AshkinTellerModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def U(self) -> float: ...
    @property
    def sigma(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the σ spin array, dtype int8."""
        ...
    @property
    def tau(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the τ spin array, dtype int8."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_four_spin_coupling(self, U: float) -> None: ...
    def set_sigma(self, site: int, value: int) -> None: ...
    def set_tau(self, site: int, value: int) -> None: ...
    def energy(self) -> float: ...
    def m_sigma(self) -> float: ...
    def abs_m_sigma(self) -> float: ...
    def m_tau(self) -> float: ...
    def abs_m_tau(self) -> float: ...
    def m_baxter(self) -> float: ...
    def abs_m_baxter(self) -> float: ...
    def _delta_energy_sigma(self, site: int) -> float: ...
    def _delta_energy_tau(self, site: int) -> float: ...
    def _metropolis_sweep(self) -> int: ...
    def _wolff_step(self) -> int: ...
    def sweep(self, n_sweeps: int) -> dict[str, npt.NDArray[np.float64]]: ...
