"""Type stubs for the C++ _core extension module."""

from typing import TypedDict

import numpy as np
import numpy.typing as npt

class PTResult(TypedDict):
    # r2t, t2r, labels are mutated in-place on the Python lists passed
    # to pt_rounds — they are NOT in this dict.
    n_accepts: list[int]
    n_attempts: list[int]
    n_up: list[int]
    n_down: list[int]
    round_trip_count: int
    obs_streams: dict[str, npt.NDArray[np.float64]]  # shape (n_slots, n_rounds)

class PT2DResult(TypedDict):
    # r2s, s2r are mutated in-place on the Python lists passed
    # to pt_rounds_2d — they are NOT in this dict.
    obs_streams: dict[str, npt.NDArray[np.float64]]  # shape (n_slots, n_rounds)
    # Per-edge acceptance counters (T-direction and param-direction).
    # T: t_accepts[j*(n_T-1) + i] = edge (i,j)↔(i+1,j)
    # P: p_accepts[i*(n_P-1) + j] = edge (i,j)↔(i,j+1)
    t_accepts: list[int]
    t_attempts: list[int]
    p_accepts: list[int]
    p_attempts: list[int]

class Rng:
    def __init__(self, seed: int) -> None: ...
    def uniform(self) -> float: ...
    def rand_below(self, n: int) -> int: ...
    def jump(self) -> None: ...

def make_neighbor_table(L: int) -> npt.NDArray[np.int32]: ...

class IsingModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def spins(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the spin array, dtype int8."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_spin(self, site: int, value: int) -> None: ...
    def energy(self) -> int: ...
    def magnetization(self) -> float: ...
    def abs_magnetization(self) -> float: ...
    def observables(self) -> dict[str, float]: ...
    def _wolff_step(self) -> int: ...
    def _delta_energy(self, site: int) -> int: ...
    def _metropolis_sweep(self) -> int: ...
    def snapshot(self) -> npt.NDArray[np.int8]:
        """(1, L, L) owning copy of the spin array."""
        ...
    def randomize(self) -> None: ...
    def sweep(self, n_sweeps: int) -> dict[str, npt.NDArray[np.int32 | np.float64]]: ...

class BlumeCapelModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def D(self) -> float: ...
    @property
    def spins(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the spin array, dtype int8."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_crystal_field(self, D: float) -> None: ...
    def set_spin(self, site: int, value: int) -> None: ...
    def energy(self) -> float: ...
    def magnetization(self) -> float: ...
    def abs_magnetization(self) -> float: ...
    def quadrupole(self) -> float: ...
    def observables(self) -> dict[str, float]: ...
    def _wolff_step(self) -> int: ...
    def _delta_energy(self, site: int, new_spin: int) -> float: ...
    def _metropolis_sweep(self) -> int: ...
    def snapshot(self) -> npt.NDArray[np.int8]:
        """(1, L, L) owning copy of the spin array."""
        ...
    def randomize(self) -> None: ...
    def sweep(self, n_sweeps: int) -> dict[str, npt.NDArray[np.float64]]: ...

class AshkinTellerModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def U(self) -> float: ...
    @property
    def sigma(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the σ spin array, dtype int8."""
        ...
    @property
    def tau(self) -> npt.NDArray[np.int8]:
        """(L, L) view into the τ spin array, dtype int8."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_four_spin_coupling(self, U: float) -> None: ...
    def set_sigma(self, site: int, value: int) -> None: ...
    def set_tau(self, site: int, value: int) -> None: ...
    def energy(self) -> float: ...
    def m_sigma(self) -> float: ...
    def abs_m_sigma(self) -> float: ...
    def m_tau(self) -> float: ...
    def abs_m_tau(self) -> float: ...
    def m_baxter(self) -> float: ...
    def abs_m_baxter(self) -> float: ...
    def observables(self) -> dict[str, float]: ...
    def _delta_energy_sigma(self, site: int) -> float: ...
    def _delta_energy_tau(self, site: int) -> float: ...
    def _metropolis_sweep(self) -> int: ...
    def _wolff_step(self) -> int: ...
    def snapshot(self) -> npt.NDArray[np.int8]:
        """(2, L, L) owning copy: channel 0=σ, channel 1=τ."""
        ...
    def randomize(self) -> None: ...
    def sweep(self, n_sweeps: int) -> dict[str, npt.NDArray[np.float64]]: ...

class XYModel:
    L: int
    @property
    def T(self) -> float: ...
    @property
    def spins(self) -> npt.NDArray[np.float64]:
        """(L, L) view into the angle array, dtype float64."""
        ...
    def __init__(self, L: int, seed: int) -> None: ...
    def set_temperature(self, T: float) -> None: ...
    def set_spin(self, site: int, angle: float) -> None: ...
    def energy(self) -> float: ...
    def mx(self) -> float: ...
    def my(self) -> float: ...
    def abs_magnetization(self) -> float: ...
    def _wolff_step(self) -> int: ...
    def _metropolis_sweep(self) -> int: ...
    def observables(self) -> dict[str, float]: ...

# --- PT engine: non-templated ------------------------------------------------

def pt_exchange(E_i: float, E_j: float, T_i: float, T_j: float, rng: Rng) -> bool: ...
def pt_exchange_param(
    dEdp_i: float,
    dEdp_j: float,
    T: float,
    param_i: float,
    param_j: float,
    rng: Rng,
) -> bool: ...

LABEL_NONE: int
LABEL_UP: int
LABEL_DOWN: int

def pt_update_labels(labels: list[int], t2r: list[int], M: int) -> None: ...
def pt_accumulate_histograms(
    n_up: list[int],
    n_down: list[int],
    labels: list[int],
    t2r: list[int],
    M: int,
) -> None: ...
def pt_count_round_trips(
    labels: list[int], prev_labels: list[int], t2r: list[int], M: int
) -> int: ...

# --- PT engine: templated per-model ------------------------------------------

def pt_exchange_round_ising(
    replicas: list[IsingModel],
    temps: list[float],
    r2t: list[int],
    t2r: list[int],
    n_accepts: list[int],
    n_attempts: list[int],
    rng: Rng,
) -> None: ...
def pt_exchange_round_bc(
    replicas: list[BlumeCapelModel],
    temps: list[float],
    r2t: list[int],
    t2r: list[int],
    n_accepts: list[int],
    n_attempts: list[int],
    rng: Rng,
) -> None: ...
def pt_exchange_round_at(
    replicas: list[AshkinTellerModel],
    temps: list[float],
    r2t: list[int],
    t2r: list[int],
    n_accepts: list[int],
    n_attempts: list[int],
    rng: Rng,
) -> None: ...

# pt_collect_obs: test-only bindings for per-T-slot observable recording
def pt_collect_obs_ising(
    obs_streams: dict[str, list[list[float]]],
    replicas: list[IsingModel],
    t2r: list[int],
    M: int,
) -> None: ...

# pt_rounds: composition loop returning PTResult as dict
def pt_rounds_ising(
    replicas: list[IsingModel],
    temps: list[float],
    r2t: list[int],
    t2r: list[int],
    labels: list[int],
    n_rounds: int,
    rng: Rng,
    track_observables: bool,
) -> PTResult: ...
def pt_rounds_bc(
    replicas: list[BlumeCapelModel],
    temps: list[float],
    r2t: list[int],
    t2r: list[int],
    labels: list[int],
    n_rounds: int,
    rng: Rng,
    track_observables: bool,
) -> PTResult: ...
def pt_rounds_at(
    replicas: list[AshkinTellerModel],
    temps: list[float],
    r2t: list[int],
    t2r: list[int],
    labels: list[int],
    n_rounds: int,
    rng: Rng,
    track_observables: bool,
) -> PTResult: ...

# --- PT engine: 2D parameter-space (BC/AT only) --------------------------------

def pt_rounds_2d_bc(
    replicas: list[BlumeCapelModel],
    temps: list[float],
    params: list[float],
    r2s: list[int],
    s2r: list[int],
    n_rounds: int,
    rng: Rng,
    track_observables: bool,
) -> PT2DResult: ...
def pt_rounds_2d_at(
    replicas: list[AshkinTellerModel],
    temps: list[float],
    params: list[float],
    r2s: list[int],
    s2r: list[int],
    n_rounds: int,
    rng: Rng,
    track_observables: bool,
) -> PT2DResult: ...
